# Generated by Django 4.1 on 2023-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('Card', models.CharField(max_length=100)),
                ('Errors', models.CharField(max_length=100)),
                ('Merchant_city', models.CharField(max_length=100)),
                ('Merchant_name', models.CharField(max_length=100)),
                ('Merchant_state', models.CharField(max_length=100)),
                ('Use_chip', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=100)),
                ('isFraud', models.CharField(max_length=100)),
            ],
        ),
    ]
