# Generated by Django 4.1 on 2023-04-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainScreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydatabase',
            old_name='isFraud',
            new_name='IsFraud',
        ),
    ]
