# Generated by Django 4.1 on 2023-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainScreen', '0002_rename_isfraud_mydatabase_isfraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydatabase',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
